### PR TITLE
feat: invert y coordinate of vector2d joystick

### PR DESCRIPTION
**Pull request by n1ru4l**

### CODE REVIEW

**Comment by gsimone** [comment]
Tiny suggestion, to make it clear that the change is for the joystick and doesn't really influence the values (if I understand that correctly)

```js
{ 
  value: [0,0], 
  joystick: {
    invertY: true
  }
}
```

**Comment by n1ru4l** [comment]
@gsimone Yes, I was also wondering on whether that makes more sense!

**Comment by dbismut** [comment]
Hm actually I was thinking:

```js
useControls({ xy: { value: [0,0], joystick: false } }) // disable joystick
useControls({ xy: { value: [0,0], joystick: 'invertY' } }) // invertY
```

Unless there's other options you'd we would like to pass to the joystick in the future, I don't think it's worth making the option an object.

**Btw, I think we should use invertY by default, I think that most of the time it makes more sense to have it in that direction, what do you guys think?**

**Comment by dbismut** [comment]
@n1ru4l I made an omission in `Joystick`, I'm importing `useDrag` from `react-use-gesture` when I actually created a custom `useDrag` utility hook in the lib that should be used: it sets `user-select: none` to the body and should prevent unfortunate text selection on Safari. Can you make the fix while you're at it?

**Comment by n1ru4l** [comment]
I agree with the "invertY" option as a string and also the invert behavior change.  I don't have any other options I would want to pass to the Joystick in mind right now and we can still change it later.

**Pull request merged**
