### PR TITLE
feat: Set inputs and folders order

### PR DESCRIPTION
**Pull request by RodrigoHamuy**
Allow to set the order in which elements appear, following a rule similar to CSS order property.

Example:

```
useControls(() => ({
  last: folder({ firstVal: 0 }, { order: 1, collapsed: true }),
  middle: folder({ secondVal: 0 }, { order: -1, collapsed: true }),
  first: { value: 0, order: -2 },
}))
```

### CODE REVIEW

**Comment by dbismut** [comment]
@RodrigoHamuy This looks really cool! I've changed the busy demo a bit to benefit from the order property. There's an issue I could spot right there. Maybe you could have a look?

image

**Comment by RodrigoHamuy** [comment]
The issue seems to consistently happen only on `string` values. When the value is a `string`, `store.getInput(path)?.settings` on[ this line](https://github.com/RodrigoHamuy/leva/blob/feat/folder-order/packages/leva/src/components/Folder/Folder.tsx#L73) does not have the `order` property. But so far, no clue why `order` is being removed and only for `string` types? :shrug:

**Comment by dbismut** [comment]
Yeah ok this might be a bug with the `string` input. Let me have a look.

**Comment by RodrigoHamuy** [comment]
I think is fixed now :ok_hand:

**Comment by dbismut** [comment]
@RodrigoHamuy I had a deep through look. The working fix you made on `string` made me realize we were handling this the right way. With common options, you can't rely on the plugin to pass them properly to settings. These are attributes you path to the input itself when you parse the input:

```json
{
  value: 0,
  settings: { min: 0, max: 10 },
  label: 'some label',
  hint: 'some hint',
  order: -1
}
```

Anyway seems like it's working but I've spotted another bug on something else and I'll use this PR to fix it.

**Pull request merged**
