### PR TITLE
Feat: plugin bezier

### PR DESCRIPTION
**Pull request by dbismut**
```js
const { curve } = useControls({ curve: bezier() })
// or
const { curve } = useControls({ curve: bezier([0.54, 0.05, 0.6, 0.98]) })
// or
const { curve } = useControls({ curve: bezier('in-out-quadratic') })
// or 
const { curve } = useControls({ curve: bezier({ handles: [0.54, 0.05, 0.6, 0.98], graph: false }) })
```

TODO:

- [x] add more presets

### CODE REVIEW

**Comment by gsimone** [comment]
Thinking about how to fix the "out of bounds" handles but coming up empty. Maybe padding is the way, but it would look a bit boring?

The main thing that google does to avoid this, is that you can click anywhere in the SVG and the closest handle snaps to that point. So you don't necessarily have to drag it and you don't have problems when the handle is not visible

**Comment by dbismut** [comment]
> The main thing that google does to avoid this, is that you can click anywhere in the SVG and the closest handle snaps to that point. So you don't necessarily have to drag it and you don't have problems when the handle is not visible

Indeed I've seen this, but if you move your handle far enough off the bounds, then you can't bring it back cause the one in view will always be the closest 🥲

There could be a similar alternative which would be to not select the _closest_ handle but rather to split the canvas in two, and select the left handle when the cursor is in the first half of the canvas, and select the right handle when the cursor is on the other half.

Note that we obviously have the coordinates fields that let you control the handles even off screen!

**Comment by gsimone** [comment]
Maybe the bezier part should be collapsible so that it would only show `Curve [ custom  ]` when closed. I might want to use a bunch of these + the spring one and it would get big!

Also, unrelated, you should use the circle version of the animation preview for the spring plugin too, it's so much better

**Comment by dbismut** [comment]
> Also, unrelated, you should use the circle version of the animation preview for the spring plugin too, it's so much better

I thought of this yesterday, but since the spring bounces a lot, I was afraid it would be confusing with the trail...?

> Maybe the bezier part should be collapsible so that it would only show Curve [ custom ] when closed. I might want to use a bunch of these + the spring one and it would get big!

I'll do the same as with the plot plugin ;)

**Pull request merged**
