### PR TITLE
feat: add condition exports

### PR DESCRIPTION
**Pull request by cbbfcd**
fixed for the [vite].

### CODE REVIEW

**Comment by dbismut** [comment]
@cbbfcd thanks for the PR. It seems like you're trying to fix the Vite demo issue. I understand there is a bit of confusion on how to make the Vite demo  run, this is on us to make it clearer. Here is the situation.

We're using `yarn workspaces` and `preconstruct` to build the packages. `preconstruct` is awesome as it streamlines the dev and build environment. In dev mode, it simply aliases the package entrypoints to their relative source files. In theory, we should be able to run the Vite demo out of the box and without issues.

However, we're facing this bug at the moment: https://github.com/preconstruct/preconstruct/issues/378. Because relative import don't resolve properly, the way we're fixing this at the moment is by running `preconstruct build && preconstruct watch` before running the Vite demo.

There is a script `yarn watch` that does all this for you and that you can run and that should set up the Vite js demo properly. Hopefully there's a way to solve the issue with `preconstruct` so that Vite js runs out of the box.

But I don't think this has to do with `exports` as `preconstruct` handles entrypoints correctly (maybe I'm missing something).

**Comment by cbbfcd** [comment]
@dbismut thanks for your explain. i got it.

**Comment by cbbfcd** [comment]
when i run `yarn watch`, i got:

```js
error: [vite:dep-scan] Failed to resolve entry for package "leva". The package may have incorrect main/module/exports specified in its package.json.
```

**Comment by dbismut** [comment]
Indeed, I get that too. At the moment I don’t have a better solution than re-running the command. We have to find a better solution though.

**Comment by dbismut** [comment]
Edit: with the new preconstruct update 2.0.6, it seems like our watch command is broken.
Try:

In one tab:
```
yarn preconstruct watch
```

In another tab:
```
yarn demo:dev
``

Sorry about this, we'll find a fix.

**Comment by cbbfcd** [comment]
ok, i will try agin

**Pull request closed without merging**
