### PR TITLE
Adds autoclose to colorpicker onMouseLeave after a 500ms delay

### PR DESCRIPTION
**Pull request by dbismut**
@marcofugaro you may want to try this see if it fits?
Related: #54

### CODE REVIEW

**Comment by marcofugaro** [comment]
nice! but please don't trigger this behaviour if the user is currently selecting a color? I mean add a check to see if the mouse is still down or something.

https://user-images.githubusercontent.com/7217420/107930279-10e47400-6f7b-11eb-9abc-9081b0b5890c.mov

**Comment by dbismut** [comment]
Right, that does make sense. So the logic would be:

- on mouse leave: if mouse button is released, trigger timeout to close. 

- on mouse up: if mouse has left the picker, close the picker immediately (or trigger timeout?)

Thanks!

**Comment by marcofugaro** [comment]
> on mouse up: if mouse has left the picker, close the picker immediately (or trigger timeout?)

I would go for close the picker immediately. To me, mouseup means the user has selected the color in the picker.

**Comment by dbismut** [comment]
@marcofugaro should be good now! It's indeed a good addition to the component. Let me know if it's good for you and I'll merge!

**Review by marcofugaro — APPROVED** [review]
Perfect! ✨

(Tested the codesandbox because the vercel deploy failed)

**Comment by dbismut** [comment]
Indeed there's something wrong with Vercel and `preconstruct` it seems. @gsimone is suspicious about it.

**Pull request merged**
