### PR TITLE
Feat: plugin plot (WIP)

### PR DESCRIPTION
**Pull request by dbismut**
The plot plugin uses [mathjs](https://mathjs.org).

https://user-images.githubusercontent.com/5003380/111231416-8890d780-85e9-11eb-972d-4bbe7bcaa750.mp4

The plot input required access to other input values, which makes it an interesting use case, which will probably require to refactor some of the API as the current state of work is pretty ugly. Cool but ugly.

### CODE REVIEW

**Comment by gsimone** [comment]
@dbismut you should add a sandbox to the PR comment so that I can look at this ⭐

**Comment by dbismut** [comment]
@gsimone there should be one actually if you look at the codesandbox CI comment?

**Comment by gsimone** [comment]
image

**Comment by gsimone** [comment]
You know what, it would be useful to show 0

image

**Comment by dbismut** [comment]
Indeed, I need to add axis + value on hover would be nice.

**Pull request merged**
